### ISSUE TITLE
Render stick figure for fall detection

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#565]
Currently fall detection events are treated as object detection events in the UI and we render [detection boxes](https://github.com/ambianic/ambianic-ui/blob/c541917ad25da8a1c191d8da1fcecd40e8b15ba7/src/views/Timeline.vue#L111) for all. Since we have the actual key points in the event data, we should render the body vectors instead of boxes for better UX.

**Comment by ivelin** [comment]
PWA receives timeline data in json format. For fall detection, the [format looks like this](https://github.com/bhavikapanara/ambianic-edge/blob/885861f1003c8ee683fd54af8b359d7720f2c8cf/tests/pipeline/test_store.py#L16).

**Comment by ivelin** [comment]
```
- args:
    datetime: '2021-03-24T05:15:57.722352'
    id: 5906a1d5bdc14a1daadd2555b39bd0f3
    image_file_name: 20210324-051557.722352-image.jpg
    inference_meta:
      display: Object Detection
    inference_result:
    - box:
        xmax: 0.7221379280090332
        xmin: 0.5994733572006226
        ymax: 0.6744111378987631
        ymin: 0.2030420502026876
      confidence: 0.97265625
      label: person
    json_file_name: 20210324-051557.722352-inference.json
    rel_dir: detections/20210324-051557.036762
    thumbnail_file_name: 20210324-051557.722352-thumbnail.jpg
  created: 1616562957.7323406
  id: f5bd750b13a44c9a9ab282e5cf075fb3
  message: Detection Event
  priority: INFO
  source_code:
    funcName: _save_sample
    lineno: 115
    pathname: /workspace/src/ambianic/pipeline/store.py
- args:
    datetime: '2021-03-24T05:15:58.891374'
    id: 1029f2dab7e449c5ae809bcaf3eb61a1
    image_file_name: 20210324-051558.891374-image.jpg
    inference_meta:
      display: Fall Detection
    inference_result:
    - confidence: 0.869477817854208
      keypoint_corr:
        left hip:
        - 136.0
        - 126.0
        left shoulder:
        - 104.0
        - 112.0
        right hip:
        - 137.0
        - 126.0
        right shoulder:
        - 96.0
        - 113.0
      label: FALL
      leaning_angle: 70.60701706840203
    json_file_name: 20210324-051558.891374-inference.json
    rel_dir: detections/20210324-051557.051711
    thumbnail_file_name: 20210324-051558.891374-thumbnail.jpg
  created: 1616562958.9004328
  id: 5af2ca2f6c024815be26968d01b5fa31
  message: Detection Event
  priority: INFO
  source_code:
    funcName: _save_sample
    lineno: 115
    pathname: /workspace/src/ambianic/pipeline/store.py
```
