### ISSUE TITLE
Improve display of idle (nothing to report) events

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#588]
**Is your feature request related to a problem? Please describe.**
Currently users can configure idle detection interval in their edge config, which causes an even to be triggered and saved (by store.py) when a particular detection has not occurred for more than a specified period of time. 

This is an optional feature but can be useful information to inform the user that the system is functioning but there is nothing to report. It could be also useful information to the user in some cases where certain activity is expected to occur at least once in a while, e.g. someone is supposed to show up to check on things once a day or once week.

Currently the timeline shows idle event as if it was a positive detection event. It confuses users because the way it renders may be mistaken for a positive detection. 

**Describe the solution you'd like**
Display something more intuitive such as "ABC has not occurred in the past XYZ hours, days, minutes (use a friendly time display format)."

**Describe alternatives you've considered**
If the user does not care for these type of idle event reports, they can turn them off in their configuration settings.

**Additional context**
Sample configuration with idle event interval:

```
     - detect_objects: # run ai inference on the input data
        ai_model: image_detection
        confidence_threshold: 0.6
        # Watch for any of the labels listed below. The labels must be from the model trained label set.
        # If no labels are listed, then watch for all model trained labels.
        label_filter:
          - person
          - car
     - save_detections: # save samples from the inference results
        positive_interval: 300 # how often (in seconds) to save samples with ANY results above the confidence threshold
        idle_interval: 6000 # how often (in seconds) to save samples with NO results above the confidence threshold
 
```
